server:
  port: 8080

spring:
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://localhost:3306/db_example?serverTimezone=UTC
    username: admin
    password: admin

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true